# Generated by Django 5.0 on 2025-07-16 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SocialApp', '0003_alter_userprofile_dob'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='following',
            field=models.ManyToManyField(related_name='followed_by', to='SocialApp.userprofile'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='block',
            field=models.ManyToManyField(related_name='block_user', to='SocialApp.userprofile'),
        ),
    ]
