# Generated by Django 5.0 on 2025-07-16 05:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SocialApp', '0004_userprofile_following_alter_userprofile_block'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='postname', to='SocialApp.posts'),
        ),
    ]
