# Generated by Django 5.0 on 2025-07-16 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SocialApp', '0005_alter_comments_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='about',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
